api: 1.14.3-R0.1-SNAPSHOT
api-version: "1.14"
main: com.buha007.spigot.bankmanager.Main
name: BankManager
version: "1.2 for MC 1.14.3"
author: Bufnita
softdepend: [Vault]
commands:
  withdraw:
    description: get your money in hand!
    usage: /withdraw <banknoteValue> <number>
  deposit:
    description: get money from hand into your account!
    usage: /deposit <banknotes amount>
  bankmanagerreload:
    description: main command of bankmanager
    usage: /bankmanager <args>
